spring:
  profiles:
    active: local

server:
  port: 8080
jwt:
  secret: temp-jwt-secret
  expiration: 10000000

---
spring:
  profiles: local
app:
  signature:
    token: 3649620B82877575A0B7D67DEBA008A0
---
spring:
  profiles: dev
app:
  signature:
    token: 3649620B82877575A0B7D67DEBA008A0

---
spring:
  profiles: test
server:
  port: 8088
app:
  signature:
    token: 3649620B82877575A0B7D67DEBA008A0

---
spring:
  profiles: prod
server:
  port: 80
app:
  signature:
    token: 3649620B82877575A0B7D67DEBA008A0